baseurl = "/"
languageCode = "en-us"
#theme = "hello-friend"
#theme = "Niello"
theme = "hello-friend-ng"
paginate = 5


[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false


[languages]
  [languages.en]
    title = "LinuxBytes"
    subtitle = "Linux Admin by day and a Coder by night"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "LinuxBytes"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"

[taxonomies]
  tag      = "tags"
  category = "categories"
