baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
#theme = "Niello"
#disableKinds = ["sitemap"]
#disableRSS = true
#theme = "terminal"
paginate = 5


[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # If you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false
  # Add Home tile
  homeSubtitle = "Linux Admin by day and a Coder by night"

[languages]
  [languages.en]
    title = "LinuxBytes"
    subtitle = "Linux Admin by day and a Coder by night"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    
    [languages.en.params.logo]
      logoText = "LinuxBytes"
      logoHomeLink = "/"
    # or
    #
    #  path = "/img/glitch-logo.GIF"
     alt = "Linux Admin by day and a Coder by night"
    # alt = "Your example logo alt text"

    [[params.social]]
      name = "github"
      url  = "https://github.com/linuxbytes"
    [[params.social]]
      name = "email"
      url  = "mailto:real8686@gmail.com"
    [[params.social]]
      name = "twitter"   
      url  = "https://twitter.com/linuxbyte3"

    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/posts"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "projects"
      #   name = "Projects"
      #   url = "/projects"


#[taxonomies]
#    category = "blog"
#    tag      = "tags"
#    series   = "series"

#[taxonomies]
#  tag      = "tags"
#  category = "categories"
[taxonomies]
  tag      = "tags"
  category = "categories"
